name: ONT-DeNovoAssembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - bcftools=1.16
  - bioawk=1.0
  - biopython=1.79
  - blinker=1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cryptography=38.0.3
  - cudatoolkit=11.1.1
  - cudnn=8.4.1.50
  - flye=2.9.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.43.2
  - grpcio=1.43.0
  - gsl=2.7
  - h5py=3.7.0
  - hdf5=1.12.2
  - htslib=1.16
  - icu=70.1
  - idna=3.4
  - importlib-metadata=5.0.0
  - intervaltree=3.0.2
  - jpeg=9e
  - k8=0.2.5
  - keras=2.7.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.39
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libprotobuf=3.19.4
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - mappy=2.24
  - markdown=3.4.1
  - markupsafe=2.1.1
  - medaka=1.7.2
  - minimap2=2.24
  - multidict=6.0.2
  - nccl=2.14.3.1
  - ncurses=6.3
  - numpy=1.19.5
  - oauthlib=3.2.2
  - ont-fast5-api=4.1.0
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - packaging=21.3
  - parasail-python=1.3.3
  - perl=5.32.1
  - pip=22.3.1
  - porechop=0.2.4
  - progressbar33=2.4
  - protobuf=3.19.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.6.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pysam=0.19.1
  - pysocks=1.7.1
  - pyspoa=0.0.3
  - python=3.8.13
  - python-edlib=1.3.9
  - python-flatbuffers=2.0
  - python_abi=3.8
  - pyu2f=0.1.5
  - re2=2022.02.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - samtools=1.16.1
  - scipy=1.9.1
  - setuptools=65.5.1
  - six=1.16.0
  - snappy=1.1.9
  - sortedcontainers=2.4.0
  - sqlite=3.39.4
  - tar=1.34
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.7.1
  - tensorflow-base=2.7.1
  - tensorflow-estimator=2.7.1
  - termcolor=2.1.0
  - tk=8.6.12
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.11
  - werkzeug=2.2.2
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.2.6
  - yarl=1.8.1
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
